### ISSUE TITLE
Product title after reviews page jump

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/storefront-product-pagination#6]
On a single product page, clicking the Customer Reviews jumps down to the reviews.  Upon scrolling back up, the product title is hidden somewhere/gone missing.  Strangest thing.  Shaking the browser around a bit, down to mobile width and back to desktop, brings back the title.  

![](http://cld.wthms.co/JyA4sB+)
http://cld.wthms.co/JyA4sB+

**Comment by jameskoster** [comment]
@mdmoore good spot! It seems to be related to how we're hiding the `h2` above the pagination links. I'll look into it.
